Update submodules pointing to invalid commits
There were 2 submodules pointing to commits that
don't exist, likely because they were overwritten
by a force push. This was causing errors for me
of the form:

error: Server does not allow request for unadvertised object 3d6e1454aac5b1ac154c7664dbccaca2e49464ac
Fetched in submodule path 'investigators/Khanlab/BigBrainMRICoreg', but it did not contain 3d6e1454aac5b1ac154c7664dbccaca2e49464ac. Direct fetching of that commit failed.

This updates those submodules to point to the hash
of the current tip of their respective repos, so
that "git submodule update --init" works.